insert into products (name, price) values ('Electric Food Steamer', 132.75);
insert into products (name, price) values ('Mini Pretzels', 67.56);
insert into products (name, price) values ('Cotton Quilted Throw Blanket', 76.45);
insert into products (name, price) values ('Smart Doorbell', 10.62);
insert into products (name, price) values ('Ethical Wool Scarf', 96.18);
insert into products (name, price) values ('Honey BBQ Riblets', 125.77);
insert into products (name, price) values ('Graphic Print Leggings', 65.67);
insert into products (name, price) values ('Cauliflower Gnocchi', 121.31);
insert into products (name, price) values ('Pet Grooming Gloves', 49.23);
insert into products (name, price) values ('Couscous', 133.18);
insert into products (name, price) values ('Portable Refrigerator Freezer', 37.62);
insert into products (name, price) values ('Almond Butter Crunch Bar', 122.11);
insert into products (name, price) values ('White Rice', 109.98);
insert into products (name, price) values ('Over-the-Door Hooks', 86.63);
insert into products (name, price) values ('Smartphone Hand Grip', 93.24);
insert into products (name, price) values ('Organic Coconut Yogurt', 20.03);
insert into products (name, price) values ('Organic Cucumber', 13.13);
insert into products (name, price) values ('Greek Yogurt', 65.24);
insert into products (name, price) values ('Chia Seed Pudding Mix', 144.96);
insert into products (name, price) values ('Coconut Milk Yogurt', 12.39);
insert into products (name, price) values ('Coconut Water', 101.66);
insert into products (name, price) values ('Adjustable Dog Harness', 45.94);
insert into products (name, price) values ('Plant Growing Kit', 63.14);
insert into products (name, price) values ('Apple Cinnamon Breakfast Muffins', 97.24);
insert into products (name, price) values ('Pumpkin Spice Creamer', 62.49);
insert into products (name, price) values ('Egg Noodles', 108.59);
insert into products (name, price) values ('Travel Pillow', 126.3);
insert into products (name, price) values ('Miso Dressing', 114.88);
insert into products (name, price) values ('Car Escape Tool', 124.01);
insert into products (name, price) values ('Mini Projector', 97.37);
insert into products (name, price) values ('Buffalo Wing Sauce', 141.04);
insert into products (name, price) values ('Outdoor Adventure Backpack', 89.85);
insert into products (name, price) values ('Satin Slip Dress', 135.79);
insert into products (name, price) values ('Stainless Steel Grater', 147.74);
insert into products (name, price) values ('Banana Nut Oatmeal Cups', 114.92);
insert into products (name, price) values ('Crafting Kit', 49.45);
insert into products (name, price) values ('Quinoa', 111.04);
insert into products (name, price) values ('Sea Salt Caramel Popcorn', 107.53);
insert into products (name, price) values ('Garden Tool Belt', 70.52);
insert into products (name, price) values ('Acoustic Guitar', 130.94);
insert into products (name, price) values ('Multifunctional Baby Bottle Warmer', 126.02);
insert into products (name, price) values ('Brown Rice', 74.8);
insert into products (name, price) values ('Crafting Kit', 114.31);
insert into products (name, price) values ('Vanilla Almond Granola', 145.51);
insert into products (name, price) values ('Eco-Friendly Yoga Mat', 58.53);
insert into products (name, price) values ('Rainbow Veggie Chips', 113.6);
insert into products (name, price) values ('Herbed Chicken Breast', 73.37);
insert into products (name, price) values ('Chickpea Salad Deluxe', 60.42);
insert into products (name, price) values ('LED Strip Lights Kit', 54.33);
insert into products (name, price) values ('Compact Pop-Up Tent', 149.84);
insert into products (name, price) values ('Smart Light Switch', 64.09);
insert into products (name, price) values ('Garden Hoses with Expandable Features', 55.95);
insert into products (name, price) values ('Honey mustard chicken tenders', 75.98);
insert into products (name, price) values ('Classic Slim Fit Shirt', 123.71);
insert into products (name, price) values ('Nutritional Yeast', 130.07);
insert into products (name, price) values ('Outdoor Adventure Kit', 36.92);
insert into products (name, price) values ('Black Olives', 105.81);
insert into products (name, price) values ('Sliced Avocado', 23.14);
insert into products (name, price) values ('Lightweight Backpacking Tent', 30.38);
insert into products (name, price) values ('Kitchen Scale', 78.11);
insert into products (name, price) values ('Baby Monitor', 87.23);
insert into products (name, price) values ('Portable Projector', 82.21);
insert into products (name, price) values ('Granola Clusters', 32.84);
insert into products (name, price) values ('Jennifer''s Amazing Lip Balm Kit', 145.01);
insert into products (name, price) values ('Teriyaki Chicken Wings', 99.13);
insert into products (name, price) values ('Art Supplies Organizer', 52.57);
insert into products (name, price) values ('LED Makeup Mirror', 32.8);
insert into products (name, price) values ('Wall Art', 104.56);
insert into products (name, price) values ('Garden Kneeler and Seat', 139.13);
insert into products (name, price) values ('Cilantro Lime Rice', 53.41);
insert into products (name, price) values ('DIY Candle Kit', 94.39);
insert into products (name, price) values ('High-Quality Yoga Block', 109.2);
insert into products (name, price) values ('Spiced Pumpkin Soup', 107.91);
insert into products (name, price) values ('Multi-Function Meat Tenderizer', 142.11);
insert into products (name, price) values ('Tuna Fish (canned)', 56.82);
insert into products (name, price) values ('Fridge Magnet Set', 50.52);
insert into products (name, price) values ('Fleece Lined Leggings', 72.77);
insert into products (name, price) values ('Carrot Ginger Soup', 31.58);
insert into products (name, price) values ('Smart Thermostat with Wi-Fi', 104.78);
insert into products (name, price) values ('Artisan Flatbreads', 148.98);
insert into products (name, price) values ('Electric Razor', 98.85);
insert into products (name, price) values ('Coconut Granola', 78.16);
insert into products (name, price) values ('Multi-Port USB Hub', 44.91);
insert into products (name, price) values ('Compact Digital Camera', 87.73);
insert into products (name, price) values ('Travel Yoga Mat', 89.0);
insert into products (name, price) values ('Fleece Hoodie', 91.16);
insert into products (name, price) values ('Green Smoothie Mix', 139.07);
insert into products (name, price) values ('Coconut Oil Spray', 58.41);
insert into products (name, price) values ('Pet Food Storage Container', 110.8);
insert into products (name, price) values ('Crafting Kit', 98.58);
insert into products (name, price) values ('Floral Summer Dress', 107.09);
insert into products (name, price) values ('Walnut Halves', 109.24);
insert into products (name, price) values ('Teriyaki Chicken Bowl', 44.91);
insert into products (name, price) values ('Toy Building Set', 61.01);
insert into products (name, price) values ('Frozen Acai Bowl', 138.37);
insert into products (name, price) values ('Honey Lemon Tea', 118.67);
insert into products (name, price) values ('Shredded Cheese', 110.27);
insert into products (name, price) values ('Rice Noodles', 106.92);
insert into products (name, price) values ('Cranberry Citrus Sauce', 136.63);
insert into products (name, price) values ('Chili Lime Corn Chips', 86.91);
insert into products (name, price) values ('Harvest Grain Salad', 72.51);
insert into products (name, price) values ('Interchangeable Watch Bands', 119.07);
insert into products (name, price) values ('Organic Chia Seeds', 114.68);
insert into products (name, price) values ('Travel Beach Blanket', 128.46);
insert into products (name, price) values ('Gardening Kneeler and Seat', 96.53);
insert into products (name, price) values ('Stainless Steel Mixing Bowls', 79.5);
insert into products (name, price) values ('Ranch Dressing', 28.1);
insert into products (name, price) values ('Gardening Tool Belt', 99.91);
insert into products (name, price) values ('Beef Taco Skillet', 19.17);
insert into products (name, price) values ('Pet Camera with Treat Dispenser', 104.87);
insert into products (name, price) values ('Lentil Soup', 120.75);
insert into products (name, price) values ('Mediterranean Chickpea Bowl', 49.9);
insert into products (name, price) values ('Instant Pot', 34.3);
insert into products (name, price) values ('Organic Cereal Bars', 95.78);
insert into products (name, price) values ('Cat Scratching Post with Toys', 74.46);
insert into products (name, price) values ('Organic Coconut Yogurt', 88.73);
insert into products (name, price) values ('Electric Screwdriver', 12.09);
insert into products (name, price) values ('High-Top Leather Boots', 81.44);
insert into products (name, price) values ('Shoe Organizer', 13.57);
insert into products (name, price) values ('Tuscan Bean Soup', 142.03);
insert into products (name, price) values ('Stylish Combat Boots', 36.12);
insert into products (name, price) values ('Cocktail Shaker Set', 65.89);
insert into products (name, price) values ('Sweet Potato Noodles', 11.97);
insert into products (name, price) values ('Poppy Seed Dressing', 114.26);
insert into products (name, price) values ('Customizable Name Plate', 37.09);
insert into products (name, price) values ('Peach Preserves', 99.52);
insert into products (name, price) values ('Sunflower Seeds', 133.5);
insert into products (name, price) values ('Pasta Portion Control Measure', 147.31);
insert into products (name, price) values ('Outdoor Adventure Backpack', 15.9);
insert into products (name, price) values ('Ceramic Bakeware Set', 84.91);
insert into products (name, price) values ('Board Game Storage', 88.25);
insert into products (name, price) values ('Pepper Jack Cheese Sticks', 48.04);
insert into products (name, price) values ('Dark Chocolate Covered Pretzels', 63.69);
insert into products (name, price) values ('Magnetic Phone Case', 92.77);
insert into products (name, price) values ('Sketchbook', 146.55);
insert into products (name, price) values ('Window Bird Feeder', 55.73);
insert into products (name, price) values ('Sparkling Blood Orange Soda', 57.25);
insert into products (name, price) values ('Ceramic Planter Set', 102.14);
insert into products (name, price) values ('Trainers with Mesh Inserts', 119.07);
insert into products (name, price) values ('Maple Bacon Jerky', 55.26);
insert into products (name, price) values ('Chocolate Chip Cookie Mix', 44.25);
insert into products (name, price) values ('Baby Monitor', 11.03);
insert into products (name, price) values ('Insulated Cooler', 52.12);
insert into products (name, price) values ('Miso Soup Mix', 55.4);
insert into products (name, price) values ('Reclining Camping Chair', 87.04);
insert into products (name, price) values ('Maple Cinnamon Granola', 112.64);
insert into products (name, price) values ('Chocolate Chip Energy Balls', 93.76);
insert into products (name, price) values ('Peach Halves (canned)', 10.22);
insert into products (name, price) values ('Pumpkin Spice Creamer', 30.17);
insert into products (name, price) values ('Spinach and Feta Wraps', 133.56);
insert into products (name, price) values ('Vegan Protein Powder', 12.67);
insert into products (name, price) values ('Digital Bullet Journal', 40.8);
insert into products (name, price) values ('Vegetable Stir-Fry Kit', 39.74);
insert into products (name, price) values ('Veggie Burger Patties', 20.46);
insert into products (name, price) values ('Organic Baby Spinach', 84.99);
insert into products (name, price) values ('Gardening Tools Set', 59.06);
insert into products (name, price) values ('Turmeric Ginger Tea', 97.49);
insert into products (name, price) values ('Salt and Pepper Grinder Set', 105.45);
insert into products (name, price) values ('Children''s Science Experiment Lab Kit', 144.98);
insert into products (name, price) values ('Collapsible Storage Crates', 84.36);
insert into products (name, price) values ('Children''s Educational Puzzle', 96.39);
insert into products (name, price) values ('Asian Noodle Salad Kit', 47.54);
insert into products (name, price) values ('Overnight Hiking Backpack', 22.05);
insert into products (name, price) values ('Cinnamon Raisin Bread', 143.82);
insert into products (name, price) values ('Aged White Cheddar Popcorn', 127.39);
insert into products (name, price) values ('Automatic Pet Feeder', 135.06);
insert into products (name, price) values ('Red Lentils', 84.63);
insert into products (name, price) values ('Brussels Sprouts', 81.96);
insert into products (name, price) values ('Interactive Robot Toy', 69.7);
insert into products (name, price) values ('Nut Butter Cups', 144.65);
insert into products (name, price) values ('Instant Read Meat Thermometer', 16.02);
insert into products (name, price) values ('Chocolate Syrup', 21.77);
insert into products (name, price) values ('Kids'' Science Experiment Kit', 38.33);
insert into products (name, price) values ('Black Bean Soup', 51.65);
insert into products (name, price) values ('Eco-Friendly Cleaning Cloths', 26.08);
insert into products (name, price) values ('Pet Water Fountain with Filtration', 47.66);
insert into products (name, price) values ('Classic BBQ Sauce', 144.36);
insert into products (name, price) values ('Cushion Covers', 63.74);
insert into products (name, price) values ('Robot Vacuum Cleaner', 74.31);
insert into products (name, price) values ('Bodyweight Resistance Bands', 54.33);
insert into products (name, price) values ('Magic Color-Changing Mug', 77.0);
insert into products (name, price) values ('Savory Trail Mix', 141.1);
insert into products (name, price) values ('Sweet Cherry Tomatoes', 75.83);
insert into products (name, price) values ('Classic Chicken Noodle Soup', 13.13);
insert into products (name, price) values ('Granola Bars', 10.24);
insert into products (name, price) values ('Organic Coconut Flour', 78.71);
insert into products (name, price) values ('Kids'' Activity Book', 107.13);
insert into products (name, price) values ('Sweet Potato Mash', 24.96);
insert into products (name, price) values ('Protein Bar Variety Pack', 87.27);
insert into products (name, price) values ('Travel Hair Straightener', 134.57);
insert into products (name, price) values ('Frozen Spinach', 21.13);
insert into products (name, price) values ('Ergonomic Mouse Pad with Wrist Support', 75.69);
insert into products (name, price) values ('Smart Water Bottle with Hydration Reminder', 105.03);
insert into products (name, price) values ('Bird Feeder', 63.68);
insert into products (name, price) values ('Blueberry Oatmeal Cups', 57.68);
insert into products (name, price) values ('Memory Foam Mattress Pad', 29.13);
insert into products (name, price) values ('Almond Flour Bread Mix', 87.51);
insert into products (name, price) values ('Spinach and Ricotta Ravioli', 19.83);
insert into products (name, price) values ('Diced Tomatoes (canned)', 47.82);
insert into products (name, price) values ('Teriyaki Sauce', 118.37);
insert into products (name, price) values ('Cinnamon Sugar Mix', 131.42);
insert into products (name, price) values ('Orange Ginger Vinaigrette', 119.5);
insert into products (name, price) values ('Caramelized Onion Dip', 51.36);
insert into products (name, price) values ('Electric Skillet', 91.49);
insert into products (name, price) values ('Bamboo Utensil Holder', 13.07);
insert into products (name, price) values ('Banana Chips', 63.13);
insert into products (name, price) values ('Garlic Naan Bread', 120.69);
insert into products (name, price) values ('Frozen Mixed Vegetables', 97.46);
insert into products (name, price) values ('Whole Grain Hamburger Buns', 110.5);
insert into products (name, price) values ('Dog Training Clicker', 120.12);
insert into products (name, price) values ('Buffalo Stilton Cheese', 55.66);
insert into products (name, price) values ('Beef Taco Skillet', 45.0);
insert into products (name, price) values ('Chocolate Avocado Pudding', 121.11);
insert into products (name, price) values ('Pumpkin Seeds', 139.0);
insert into products (name, price) values ('Quality Chef Apron', 148.71);
insert into products (name, price) values ('Wireless Gaming Mouse', 44.43);
insert into products (name, price) values ('Biodegradable Dog Waste Bags', 124.02);
insert into products (name, price) values ('Fashionable Fanny Pack', 114.1);
insert into products (name, price) values ('Herbal Tea Sampler Box', 135.52);
insert into products (name, price) values ('Smartphone Hand Grip', 20.46);
insert into products (name, price) values ('Creamy Tomato Basil Soup', 149.62);
insert into products (name, price) values ('Collapsible Colander', 142.0);
insert into products (name, price) values ('Fresh Cilantro', 36.14);
insert into products (name, price) values ('Frozen Broccoli', 31.17);
insert into products (name, price) values ('Oversized Denim Shirt', 131.76);
insert into products (name, price) values ('Sriracha Hot Chili Sauce', 36.54);
insert into products (name, price) values ('Pasta Sauce Mix', 28.4);
insert into products (name, price) values ('Compact Umbrella', 43.19);
insert into products (name, price) values ('Savory Oatmeal Cups', 84.06);
insert into products (name, price) values ('Lemon Basil Pasta Sauce', 18.41);
insert into products (name, price) values ('Educational STEM Kit', 97.59);
insert into products (name, price) values ('Chiffon Blouse', 26.09);
insert into products (name, price) values ('Digital Camera', 142.25);
insert into products (name, price) values ('Pumpkin Spice Muffins', 22.7);
insert into products (name, price) values ('High-Pressure Handheld Shower Head', 131.98);
insert into products (name, price) values ('Bamboo Cotton Tank Top', 64.71);
insert into products (name, price) values ('Dog Collar', 15.35);
insert into products (name, price) values ('Cabbage', 43.26);
insert into products (name, price) values ('Ranch Dressing', 28.24);
insert into products (name, price) values ('Portable Solar Path Lights', 130.11);
insert into products (name, price) values ('Pet Food Storage Container', 77.08);
insert into products (name, price) values ('Lemon Herb Grilled Chicken', 145.22);
insert into products (name, price) values ('Pet Food Storage Container', 130.46);
insert into products (name, price) values ('Spicy Italian Sausage', 12.85);
insert into products (name, price) values ('Personal Safety Alarm', 36.46);
insert into products (name, price) values ('Adjustable Pet Feeder', 38.46);
insert into products (name, price) values ('LED Disco Ball Light', 131.08);
insert into products (name, price) values ('Maple Almond Granola', 86.59);
insert into products (name, price) values ('LED Strip Lights', 33.13);
insert into products (name, price) values ('Window Bird Feeder with Suction Cups', 81.68);
insert into products (name, price) values ('Warm Wool Sweater', 111.83);
insert into products (name, price) values ('Avocado Oil', 62.91);
insert into products (name, price) values ('Apricot Jam', 113.45);
insert into products (name, price) values ('Smart Air Purifier', 110.32);
insert into products (name, price) values ('Dill Pickle Chips', 120.48);
insert into products (name, price) values ('Hummus Variety Pack', 66.04);
insert into products (name, price) values ('Teriyaki Tofu Stir-Fry', 90.09);
insert into products (name, price) values ('Throw Pillow Covers', 139.1);
insert into products (name, price) values ('Mediterranean Couscous', 128.8);
insert into products (name, price) values ('Fruit & Nut Trail Mix', 34.48);
insert into products (name, price) values ('Pet Travel Bed', 127.83);
insert into products (name, price) values ('Faux Leather Leggings', 96.93);
insert into products (name, price) values ('Vegetable Broth', 17.79);
insert into products (name, price) values ('Pet Travel Bed', 120.68);
insert into products (name, price) values ('Ice Cream', 43.94);
insert into products (name, price) values ('LED Desk Lamp', 16.24);
insert into products (name, price) values ('Cranberry Almond Granola', 118.59);
insert into products (name, price) values ('Sliced Olives', 27.56);
insert into products (name, price) values ('Red Lentil Pasta', 94.78);
insert into products (name, price) values ('Mini Hand Gesture Drone', 15.37);
insert into products (name, price) values ('Outdoor Camping Hammock', 46.05);
insert into products (name, price) values ('Pet Safety Harness', 38.72);
insert into products (name, price) values ('Wireless Charging Station', 136.78);
insert into products (name, price) values ('Portable Solar Charger', 43.81);
insert into products (name, price) values ('Solar Power Bank', 99.27);
insert into products (name, price) values ('Cauliflower Gnocchi', 32.39);
insert into products (name, price) values ('Organic Green Lentils', 131.88);
insert into products (name, price) values ('Suction Cup Hooks', 42.92);
insert into products (name, price) values ('Organic Vanilla Bean Ice Cream', 130.84);
insert into products (name, price) values ('Lemon Herb Grilled Chicken', 107.21);
insert into products (name, price) values ('Colorful Post-It Notes Set', 12.49);
insert into products (name, price) values ('Personal Blender', 58.91);
insert into products (name, price) values ('Kale and Quinoa Salad', 48.04);
insert into products (name, price) values ('Brown Sugar', 66.18);
insert into products (name, price) values ('Thai Peanut Dressing', 64.96);
insert into products (name, price) values ('DIY Organic Gardening Kit', 115.07);
insert into products (name, price) values ('LED Canopy Lights', 60.7);
insert into products (name, price) values ('Coconut Water', 13.03);
insert into products (name, price) values ('Flavored Rice Cakes', 78.68);
insert into products (name, price) values ('Indian Curry Sauce', 87.71);
insert into products (name, price) values ('Smart Light Bulbs', 115.86);
insert into products (name, price) values ('Kombucha Drink', 144.52);
insert into products (name, price) values ('Lemon Sorbet', 109.94);
insert into products (name, price) values ('Backpack', 33.04);
insert into products (name, price) values ('Foam Muscle Roller', 52.37);
insert into products (name, price) values ('Electric Stool Heater', 12.64);
insert into products (name, price) values ('Organic Tomato Soup', 108.84);
insert into products (name, price) values ('Bamboo Charcoal Air Purifier Bags', 97.36);
insert into products (name, price) values ('Smartphone Projector', 90.33);
insert into products (name, price) values ('Beef Stew Meat', 49.5);
insert into products (name, price) values ('Bock Beer Mustard', 24.68);
insert into products (name, price) values ('Electric Food Slicer', 68.69);
insert into products (name, price) values ('Stainless Steel Water Pitcher', 15.98);
insert into products (name, price) values ('Personalized Keychain', 47.25);
insert into products (name, price) values ('Italian Breadsticks', 31.46);
insert into products (name, price) values ('Frozen Mixed Berries', 102.69);
insert into products (name, price) values ('Chili Con Carne Mix', 101.92);
insert into products (name, price) values ('Roasted Garlic Aioli', 122.44);
insert into products (name, price) values ('Personalized Pet ID Tags', 105.2);
insert into products (name, price) values ('Infrared Thermometer', 36.46);
insert into products (name, price) values ('Pet Grooming Gloves', 40.01);
insert into products (name, price) values ('Microfiber Cleaning Cloths', 147.54);
insert into products (name, price) values ('Dried Apricots', 101.98);
insert into products (name, price) values ('Teriyaki Stir-Fry Sauce', 46.74);
insert into products (name, price) values ('Tomato Basil Pasta Sauce', 18.31);
insert into products (name, price) values ('Pet Travel Carrier', 76.7);
insert into products (name, price) values ('Collapsible Storage Crates', 74.62);
insert into products (name, price) values ('Honeycrisp Apple Chips', 23.8);
insert into products (name, price) values ('Weighted Jump Rope with Counter', 81.18);
insert into products (name, price) values ('Mango Salsa', 136.3);
insert into products (name, price) values ('Cold Brew Coffee Concentrate', 102.55);
insert into products (name, price) values ('Sweet Pea Hummus', 108.81);
insert into products (name, price) values ('Fitness Foam Roller', 144.69);
insert into products (name, price) values ('Silicone Baking Molds', 132.81);
insert into products (name, price) values ('Chocolate Coconut Granola', 134.62);
insert into products (name, price) values ('Smart Home Hub', 62.65);
insert into products (name, price) values ('Spinach and Ricotta Ravioli', 94.35);
insert into products (name, price) values ('Cheddar Cheese Slices', 109.76);
insert into products (name, price) values ('Running Shorts', 62.97);
insert into products (name, price) values ('Frozen Salmon Filets', 113.21);
insert into products (name, price) values ('Folding Pocket Knife', 148.74);
insert into products (name, price) values ('Asian Stir-Fry Vegetables', 44.75);
insert into products (name, price) values ('Foam Building Blocks for Kids', 96.26);
insert into products (name, price) values ('Olive Oil', 84.66);
insert into products (name, price) values ('Scented Soy Candles', 37.29);
insert into products (name, price) values ('Dog Training Clicker', 118.4);
insert into products (name, price) values ('Apple Cinnamon Oatmeal', 122.92);
insert into products (name, price) values ('Stainless Steel BBQ Grill Set', 23.08);
insert into products (name, price) values ('Pocket Blanket', 71.38);
insert into products (name, price) values ('Organic Baby Spinach', 86.39);
insert into products (name, price) values ('Body Wash', 55.39);
insert into products (name, price) values ('Eco-Friendly Stainless Steel Straws', 48.16);
insert into products (name, price) values ('Art Supplies Organizer', 60.93);
insert into products (name, price) values ('Smart Scale', 31.74);
insert into products (name, price) values ('Bike Helmet', 135.3);
insert into products (name, price) values ('Maple Cinnamon Almonds', 109.08);
insert into products (name, price) values ('Frozen Vegetarian Pizza', 27.77);
insert into products (name, price) values ('Couscous Mix', 99.5);
insert into products (name, price) values ('Lentil Vegetable Stew', 130.29);
insert into products (name, price) values ('Blender Bottle', 102.74);
insert into products (name, price) values ('Customizable Name Plate', 77.72);
insert into products (name, price) values ('Basil-infused Olive Oil', 85.06);
insert into products (name, price) values ('Spicy Hummus', 133.24);
insert into products (name, price) values ('Frozen Mixed Berries', 76.2);
insert into products (name, price) values ('Red Lentil Pasta', 40.61);
insert into products (name, price) values ('Pet Food Storage Container', 25.66);
insert into products (name, price) values ('Almond Crunch Granola Bars', 112.12);
insert into products (name, price) values ('Kids'' Activity Book', 76.05);
insert into products (name, price) values ('LED Christmas Tree Lights', 49.07);
insert into products (name, price) values ('Creamy Coleslaw Mix', 70.94);
insert into products (name, price) values ('Dried Apricots', 137.13);
insert into products (name, price) values ('Wrist Support Brace', 50.21);
insert into products (name, price) values ('Chicken Breasts', 85.53);
insert into products (name, price) values ('Lightweight Workout Tank', 102.42);
insert into products (name, price) values ('Whisk Set', 96.05);
insert into products (name, price) values ('Nutty Granola Clusters', 139.31);
insert into products (name, price) values ('Cooking Utensil Set', 14.15);
insert into products (name, price) values ('Frozen Cauliflower Rice', 23.34);
insert into products (name, price) values ('Coconut Cream Pie Mix', 141.89);
insert into products (name, price) values ('Apple Juice', 21.85);
insert into products (name, price) values ('Infrared Thermometer Gun', 23.12);
insert into products (name, price) values ('Couscous Mix', 148.47);
insert into products (name, price) values ('Portable SSD', 28.82);
insert into products (name, price) values ('Chicken Broth', 80.84);
insert into products (name, price) values ('Handheld Garment Steamer', 11.15);
insert into products (name, price) values ('Multi-Port USB Hub', 60.44);
insert into products (name, price) values ('Electric Griddle with Removable Plates', 59.29);
insert into products (name, price) values ('Kitchen Knife Sharpening System', 122.66);
insert into products (name, price) values ('Spicy Chicken Wings', 56.37);
insert into products (name, price) values ('Mixed Berry Smoothie Pack', 94.23);
insert into products (name, price) values ('Organic Black Rice', 111.56);
insert into products (name, price) values ('Pet Travel Carrier', 108.01);
insert into products (name, price) values ('Gingerbread House Kit', 25.88);
insert into products (name, price) values ('Hot Dog Buns', 11.73);
insert into products (name, price) values ('Chocolate Protein Powder', 145.71);
insert into products (name, price) values ('Mechanical Pencil Set', 130.46);
insert into products (name, price) values ('Non-Stick Baking Sheets', 34.28);
insert into products (name, price) values ('Over-Ear Headphones', 77.33);
insert into products (name, price) values ('Travel Sewing Kit', 106.15);
insert into products (name, price) values ('Natural Fruit Snacks', 129.99);
insert into products (name, price) values ('Ginger Tea', 17.94);
insert into products (name, price) values ('Classic Caesar Salad Kit', 87.47);
insert into products (name, price) values ('Dried Apricots', 16.5);
insert into products (name, price) values ('Eco-Friendly Stainless Steel Straws', 77.74);
insert into products (name, price) values ('Oatmeal Raisin Cookies', 133.61);
insert into products (name, price) values ('Fruit & Nut Trail Mix', 61.84);
insert into products (name, price) values ('Cable Knit Cardigan', 16.31);
insert into products (name, price) values ('Educational STEM Kit', 16.73);
insert into products (name, price) values ('Luxury Bathrobe', 100.61);
insert into products (name, price) values ('Wireless HDMI Receiver', 78.06);
insert into products (name, price) values ('Chili Lime Seasoning', 29.15);
insert into products (name, price) values ('Fitness Jump Box', 133.63);
insert into products (name, price) values ('Decorative Wall Tapestry', 82.46);
insert into products (name, price) values ('Chili Lime Seasoning', 125.06);
insert into products (name, price) values ('Foldable Yoga Mat Carry Bag', 130.32);
insert into products (name, price) values ('Garlic Butter Sauce', 130.23);
insert into products (name, price) values ('Falafel Mix', 145.98);
insert into products (name, price) values ('Smartphone UV Sanitizer', 142.8);
insert into products (name, price) values ('Coconut Oil Spray', 117.81);
insert into products (name, price) values ('Creamy Avocado Dip', 21.3);
insert into products (name, price) values ('Thyme', 124.55);
insert into products (name, price) values ('Mixed Berry Smoothie Pack', 128.46);
insert into products (name, price) values ('Wall-Mounted Spice Rack', 111.5);
insert into products (name, price) values ('Linen Trousers', 144.13);
insert into products (name, price) values ('Tennis Racket', 122.2);
insert into products (name, price) values ('Customizable Photo Calendar', 88.17);
insert into products (name, price) values ('Organic Coconut Yogurt', 85.53);
insert into products (name, price) values ('Oven Thermometer', 69.75);
insert into products (name, price) values ('Rice Cakes', 112.87);
insert into products (name, price) values ('Stick Vacuums Cleaner', 117.06);
insert into products (name, price) values ('Coconut Cashew Yogurt', 87.75);
insert into products (name, price) values ('Eggs (dozen)', 15.46);
insert into products (name, price) values ('Self-Inflating Camping Mattress', 147.93);
insert into products (name, price) values ('Baking Soda', 81.66);
insert into products (name, price) values ('Creamy Garlic Dressing', 13.71);
insert into products (name, price) values ('Peanut Butter Filled Pretzels', 16.41);
insert into products (name, price) values ('Raspberry Vanilla Greek Yogurt', 141.02);
insert into products (name, price) values ('Dog Training Whistle', 134.43);
insert into products (name, price) values ('Gardening Gloves with Claws', 115.15);
insert into products (name, price) values ('Sweet Potato Noodles', 104.39);
insert into products (name, price) values ('Relaxed Fit Henley Shirt', 12.0);
insert into products (name, price) values ('Popcorn Chicken', 94.24);
insert into products (name, price) values ('Vegan Protein Powder', 122.67);
insert into products (name, price) values ('Cork Yoga Mat', 57.87);
insert into products (name, price) values ('Wireless HDMI Receiver', 91.06);
insert into products (name, price) values ('Spiced Pumpkin Soup', 61.43);
insert into products (name, price) values ('Heavy-Duty Utility Tote', 135.76);
insert into products (name, price) values ('Noise-Canceling Headphones', 33.5);
insert into products (name, price) values ('Cinnamon Sugar Tortilla Chips', 136.29);
insert into products (name, price) values ('Savory Pumpkin Soup', 67.13);
insert into products (name, price) values ('Electric Kettle with Temperature Control', 119.89);
insert into products (name, price) values ('Pear and Gorgonzola Salad', 74.43);
insert into products (name, price) values ('Comfort Flats', 19.1);
insert into products (name, price) values ('Marinara Parmesan Baked Ziti', 129.4);
insert into products (name, price) values ('Whisk Set', 127.17);
insert into products (name, price) values ('Smartphone Gimbal Stabilizer', 56.09);
insert into products (name, price) values ('Dog Car Seat Cover', 11.54);
insert into products (name, price) values ('Ultraviolet Phone Sanitizer', 80.07);
insert into products (name, price) values ('Drone', 108.5);
insert into products (name, price) values ('French Bread', 70.34);
